-- 集成测试专用 schema（仅本机测试容器使用，不触碰任何生产/预置库）。
-- 由 IntegrationTest 在建立 Spring 上下文前执行；SQL 与 deploy/mysql/hnieoj_多数据库.sql 中对应表保持一致。

DROP TABLE IF EXISTS `judge_task_execution`;
DROP TABLE IF EXISTS `judge_task_outbox`;
DROP TABLE IF EXISTS `judge_case`;
DROP TABLE IF EXISTS `judge`;
DROP TABLE IF EXISTS `judge_node_key`;
DROP TABLE IF EXISTS `judge_node_token`;
DROP TABLE IF EXISTS `judge_node_auth_code`;
DROP TABLE IF EXISTS `rejudge_task_detail`;
DROP TABLE IF EXISTS `rejudge_task`;

CREATE TABLE `judge` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `submit_id` varchar(64) NOT NULL,
  `judge_task_id` varchar(64) DEFAULT NULL,
  `problem_id` bigint(20) NOT NULL,
  `problem_code` varchar(50) NOT NULL,
  `uid` varchar(50) NOT NULL,
  `username` varchar(100) NOT NULL,
  `language` varchar(20) NOT NULL,
  `code` longtext NOT NULL,
  `status` int(11) DEFAULT '-10',
  `error_message` text,
  `diagnostic_message` text,
  `time` int(11) DEFAULT NULL,
  `memory` int(11) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `cid` bigint(20) DEFAULT '0',
  `total_case` int(11) DEFAULT '0',
  `judged_case` int(11) DEFAULT '0',
  `current_case` int(11) DEFAULT '0',
  `cpid` bigint(20) DEFAULT '0',
  `tid` bigint(20) DEFAULT '0',
  `hid` bigint(20) DEFAULT '0',
  `judger` varchar(50) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `is_manual` tinyint(1) DEFAULT '0',
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_submit_id` (`submit_id`),
  KEY `idx_judge_task_id` (`judge_task_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_case` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `submit_id` bigint(20) NOT NULL,
  `case_id` varchar(20) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `time` int(11) DEFAULT NULL,
  `memory` int(11) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `input_data` varchar(255) DEFAULT NULL,
  `output_data` varchar(255) DEFAULT NULL,
  `user_output` text,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_submit_id` (`submit_id`),
  UNIQUE KEY `uk_submit_case` (`submit_id`, `case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_task_outbox` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `message_id` varchar(64) NOT NULL,
  `judge_task_id` varchar(64) NOT NULL,
  `submission_id` varchar(64) NOT NULL,
  `exchange_name` varchar(128) NOT NULL,
  `routing_key` varchar(128) NOT NULL,
  `stream_key` varchar(128) DEFAULT NULL,
  `stream_id` varchar(64) DEFAULT NULL,
  `payload` longtext NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `retry_count` int(11) NOT NULL DEFAULT '0',
  `publish_attempt` int(11) NOT NULL DEFAULT '0',
  `max_retry_count` int(11) NOT NULL DEFAULT '10',
  `next_retry_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `sent_time` datetime DEFAULT NULL,
  `last_error` text,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_message_id` (`message_id`),
  KEY `idx_status_next_retry` (`status`, `next_retry_time`),
  KEY `idx_judge_task_id` (`judge_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_task_execution` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `submission_id` varchar(64) NOT NULL,
  `judge_id` bigint(20) NOT NULL,
  `judge_task_id` varchar(64) NOT NULL,
  `problem_id` bigint(20) NOT NULL,
  `problem_code` varchar(50) DEFAULT NULL,
  `judge_mode` varchar(20) NOT NULL DEFAULT 'default',
  `stream_key` varchar(128) NOT NULL,
  `stream_id` varchar(64) DEFAULT NULL,
  `node_id` varchar(64) DEFAULT NULL,
  `token_id` varchar(64) DEFAULT NULL,
  `session_epoch` bigint(20) DEFAULT NULL,
  `attempt_id` varchar(64) DEFAULT NULL,
  `attempt_count` int(11) NOT NULL DEFAULT '0',
  `max_attempt_count` int(11) NOT NULL DEFAULT '3',
  `status` varchar(20) NOT NULL DEFAULT 'queued',
  `lease_until` bigint(20) DEFAULT NULL,
  `renew_after_millis` int(11) DEFAULT NULL,
  `execution_deadline` bigint(20) DEFAULT NULL,
  `last_error` varchar(512) DEFAULT NULL,
  `terminal_fingerprint` varchar(64) DEFAULT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_submission_id` (`submission_id`),
  KEY `idx_status_lease` (`status`, `lease_until`),
  KEY `idx_node_status` (`node_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_node_token` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `token_id` varchar(64) NOT NULL,
  `node_id` varchar(64) NOT NULL,
  `node_name` varchar(100) DEFAULT NULL,
  `node_type` varchar(20) NOT NULL,
  `status` varchar(20) DEFAULT 'active',
  `auth_code_id` bigint(20) DEFAULT NULL,
  `instance_id` varchar(64) DEFAULT NULL,
  `fingerprint_hash` varchar(64) DEFAULT NULL,
  `bound_source_ip` varchar(64) DEFAULT NULL,
  `proof_type` varchar(32) DEFAULT NULL,
  `public_key` text DEFAULT NULL,
  `public_key_hash` varchar(64) DEFAULT NULL,
  `expire_time` datetime(3) NOT NULL,
  `last_used_time` datetime DEFAULT NULL,
  `last_heartbeat_time` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `last_seen_ip` varchar(64) DEFAULT NULL,
  `max_concurrency` int(11) DEFAULT NULL,
  `running_tasks` bigint(20) DEFAULT NULL,
  `cpu_core` int(11) DEFAULT NULL,
  `version` varchar(100) DEFAULT NULL,
  `supported_judge_modes` varchar(255) DEFAULT 'default',
  `diagnostic_message` text DEFAULT NULL,
  `cache_used_bytes` bigint(20) DEFAULT NULL,
  `cache_problem_count` int(11) DEFAULT NULL,
  `disk_total_bytes` bigint(20) DEFAULT NULL,
  `disk_free_bytes` bigint(20) DEFAULT NULL,
  `revoked_time` datetime DEFAULT NULL,
  `revoked_by` varchar(50) DEFAULT NULL,
  `session_epoch` bigint(20) NOT NULL DEFAULT '0',
  `access_version` int(11) NOT NULL DEFAULT '0',
  `active_key_id` varchar(64) DEFAULT NULL,
  `weight` int(11) NOT NULL DEFAULT '10',
  `draining` tinyint(1) NOT NULL DEFAULT '0',
  `authorization_until` datetime(3) DEFAULT NULL,
  `enrollment_id` varchar(64) DEFAULT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_token_id` (`token_id`),
  UNIQUE KEY `uk_node_enrollment` (`enrollment_id`),
  KEY `idx_node_id` (`node_id`),
  KEY `idx_active_key_id` (`active_key_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_node_key` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `key_id` varchar(64) NOT NULL,
  `node_id` varchar(64) NOT NULL,
  `public_key` varchar(128) NOT NULL,
  `public_key_hash` varchar(64) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `rotation_id` varchar(64) DEFAULT NULL,
  `confirm_nonce` varchar(128) DEFAULT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `previous_key_id` varchar(64) DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `revoked_time` datetime DEFAULT NULL,
  `revoked_by` varchar(50) DEFAULT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_key_id` (`key_id`),
  UNIQUE KEY `uk_node_rotation` (`node_id`, `rotation_id`),
  KEY `idx_node_status` (`node_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `judge_node_auth_code` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code_hash` varchar(128) NOT NULL,
  `node_name` varchar(100) DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `max_exchange_count` int(11) DEFAULT '1',
  `used_count` int(11) DEFAULT '0',
  `status` varchar(20) DEFAULT 'enabled',
  `expire_time` datetime(3) NOT NULL,
  `node_type` varchar(20) NOT NULL DEFAULT 'temp',
  `policy_json` text DEFAULT NULL,
  `authorization_until` datetime(3) DEFAULT NULL,
  `enrollment_id` varchar(64) DEFAULT NULL,
  `public_key_hash` varchar(64) DEFAULT NULL,
  `node_id` varchar(64) DEFAULT NULL,
  `consumed_time` datetime DEFAULT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_hash` (`code_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rejudge_task_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` bigint(20) NOT NULL,
  `judge_id` bigint(20) NOT NULL,
  `submit_id` varchar(64) NOT NULL,
  `problem_id` bigint(20) NOT NULL,
  `problem_code` varchar(50) NOT NULL,
  `uid` varchar(50) NOT NULL,
  `username` varchar(100) DEFAULT NULL,
  `language` varchar(50) NOT NULL,
  `original_status` int(11) NOT NULL,
  `original_score` int(11) DEFAULT NULL,
  `original_time` int(11) DEFAULT NULL,
  `original_memory` int(11) DEFAULT NULL,
  `judge_task_id` varchar(64) DEFAULT NULL,
  `final_status` int(11) DEFAULT NULL,
  `final_score` int(11) DEFAULT NULL,
  `final_time` int(11) DEFAULT NULL,
  `final_memory` int(11) DEFAULT NULL,
  `finished_time` datetime DEFAULT NULL,
  `submit_time` datetime DEFAULT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_judge` (`task_id`, `judge_id`),
  KEY `idx_judge_id` (`judge_id`),
  KEY `idx_judge_task_id` (`judge_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rejudge_task` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `problem_id` bigint(20) NOT NULL,
  `problem_code` varchar(50) NOT NULL,
  `contest_id` bigint(20) DEFAULT NULL,
  `range_start` datetime DEFAULT NULL,
  `range_end` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `total_count` int(11) NOT NULL DEFAULT '0',
  `processed_count` int(11) NOT NULL DEFAULT '0',
  `failed_count` int(11) NOT NULL DEFAULT '0',
  `last_judge_id` bigint(20) NOT NULL DEFAULT '0',
  `last_error` text,
  `locked_by` varchar(128) DEFAULT NULL,
  `lock_until` datetime DEFAULT NULL,
  `admin_id` varchar(50) NOT NULL,
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_status_id` (`status`, `id`),
  KEY `idx_status_lock` (`status`, `lock_until`),
  KEY `idx_problem_id` (`problem_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
