mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: Authorization
  token-prefix: Bearer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

hnieoj:
  judge:
    security:
      jwt-secret: ${HNIEOJ_JUDGE_JWT_SECRET:replace_me}
