spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hnieoj.mysql.host}:${hnieoj.mysql.port}/hnieoj_judge_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${hnieoj.mysql.username}
    password: ${hnieoj.mysql.password}
  data:
    redis:
      host: ${hnieoj.redis.host}
      port: ${hnieoj.redis.port}
      password: ${hnieoj.redis.password}

sa-token:
  is-print: false

# 本地调试
hnieoj:
  submission:
    websocket:
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "http://127.0.0.1:3000"
        - "http://127.0.0.1:5173"
