hnieoj:
  mysql:
    host: ${MYSQL_HOST:127.0.0.1}
    port: ${MYSQL_PORT:3306}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:replace_me}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:replace_me}
  internal:
    token: ${HNIEOJ_INTERNAL_TOKEN:replace_me}
